import { FormEvent, useEffect, useMemo, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { Archive, CalendarDays, Camera, Clapperboard, Clock3, Edit3, Film, Heart, Home, LogOut, MapPin, Menu, Plus, Settings, Sparkles, Trash2, UserRound, X } from 'lucide-react'
import Auth from './components/Auth'
import Galaxy from './components/Galaxy'
import Tamagotchi from './components/Tamagotchi'
import { compliments, museumRooms, timeline } from './data'
import { supabase } from './lib/supabase'
import type { Artifact, Movie, Photo, Profile } from './types'

type View = 'home'|'calendar'|'museum'|'gallery'|'movies'|'galaxy'|'admin'|'profile'
const nav: {id:View;label:string;icon:typeof Home}[] = [
  {id:'home',label:'Главная',icon:Home},{id:'calendar',label:'Календарь',icon:CalendarDays},{id:'museum',label:'Музей',icon:Archive},{id:'gallery',label:'Наши фото',icon:Camera},
  {id:'movies',label:'Фильмы',icon:Clapperboard},{id:'galaxy',label:'Галактика Вики',icon:Sparkles},{id:'admin',label:'Управление',icon:Settings}
]
const togetherSince = new Date('2026-07-07T00:00:00+03:00')
const tripDate = new Date('2026-09-18T00:00:00+02:00')
const daysBetween = (from: Date, to = new Date()) => Math.max(0, Math.floor((to.getTime()-from.getTime())/86400000))
const filePath = (file: File) => `${Date.now()}-${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`

export default function App() {
  const [session,setSession]=useState<Session|null>(null), [loading,setLoading]=useState(true), [view,setView]=useState<View>('home'), [mobile,setMobile]=useState(false)
  const [photos,setPhotos]=useState<Photo[]>([]), [movies,setMovies]=useState<Movie[]>([]), [artifacts,setArtifacts]=useState<Artifact[]>([]), [profile,setProfile]=useState<Profile|null>(null)
  const load = async () => {
    const currentUser = (await supabase.auth.getUser()).data.user
    const [p,m,a,pr] = await Promise.all([
      supabase.from('photos').select('*').order('created_at',{ascending:false}), supabase.from('movies').select('*').order('created_at',{ascending:false}),
      supabase.from('artifacts').select('*').order('created_at',{ascending:false}), supabase.from('profiles').select('*').eq('id',currentUser?.id||'').maybeSingle()
    ])
    if(p.data)setPhotos(p.data); if(m.data)setMovies(m.data); if(a.data)setArtifacts(a.data); if(pr.data)setProfile(pr.data)
  }
  useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false);if(data.session)load()});const {data}=supabase.auth.onAuthStateChange((_e,s)=>{setSession(s);if(s)load()});return()=>data.subscription.unsubscribe()},[])
  if(loading)return <div className="splash"><Heart fill="currentColor"/><span>thugger × vichka</span></div>
  if(!session)return <Auth/>
  return <div className="app-shell">
    <aside className={mobile?'open':''}><div className="brand"><Heart fill="currentColor"/><div><strong>thugger <i>×</i> vichka</strong><span>НАША ВСЕЛЕННАЯ</span></div><button className="mobile-close" onClick={()=>setMobile(false)}><X/></button></div>
      <nav>{nav.map(({id,label,icon:Icon})=><button className={view===id?'active':''} key={id} onClick={()=>{setView(id);setMobile(false)}}><Icon size={19}/>{label}</button>)}</nav>
      <button className="user-mini" onClick={()=>setView('profile')}><div className="avatar">{profile?.avatar_url?<img src={profile.avatar_url}/>:<UserRound/>}</div><div><b>{profile?.display_name||session.user.email?.split('@')[0]}</b><span>Открыть профиль</span></div></button>
    </aside>
    {mobile&&<button className="scrim" onClick={()=>setMobile(false)}/>}
    <main className="main"><header><button className="menu" onClick={()=>setMobile(true)}><Menu/></button><div><span>PRIVATE ARCHIVE</span><b>07 · 07 · 2026</b></div><button className="profile-button" onClick={()=>setView('profile')}><UserRound size={18}/>{profile?.display_name||'Профиль'}</button></header>
      {view==='home'&&<HomeView photos={photos} setView={setView}/>} {view==='calendar'&&<CalendarView/>} {view==='museum'&&<Museum artifacts={artifacts}/>} {view==='gallery'&&<Gallery photos={photos}/>} {view==='movies'&&<Movies movies={movies}/>} {view==='galaxy'&&<GalaxyPage/>}
      {view==='admin'&&<Admin photos={photos} movies={movies} artifacts={artifacts} reload={load}/>} {view==='profile'&&<ProfileView profile={profile} reload={load}/>} 
    </main>
  </div>
}

function HomeView({photos,setView}:{photos:Photo[];setView:(v:View)=>void}) {
  const day=daysBetween(togetherSince), compliment=compliments[day%compliments.length], trip=Math.ceil((tripDate.getTime()-Date.now())/86400000)
  return <div className="page home-page"><section className="hero"><div className="hero-copy"><p className="eyebrow">НАША ИСТОРИЯ · ГЛАВА {String(day+1).padStart(3,'0')}</p><h1>Ты — моё любимое<br/><em>расстояние.</em></h1><p>Между Москвой и Калининградом 1 090 км. Между нами — ни одного.</p><button className="primary" onClick={()=>setView('museum')}>Начать экскурсию <span>→</span></button></div><div className="orbit"><div className="orbit-ring one"/><div className="orbit-ring two"/><Heart className="orbit-heart" fill="currentColor"/><span className="city moscow">МОСКВА<i/></span><span className="city kaliningrad">КАЛИНИНГРАД<i/></span></div></section>
    <section className="stats"><div><strong>{day}</strong><span>дней вместе</span></div><div><strong>1 090</strong><span>километров между нами</span></div><div><strong>{trip>0?trip:0}</strong><span>{trip>0?'дней до встречи':'дней мечта стала реальностью'}</span></div><div><strong>∞</strong><span>причин любить тебя</span></div></section>
    <section className="compliment"><div className="quote">“</div><div><p className="eyebrow">КОМПЛИМЕНТ ДНЯ · #{day+1}</p><blockquote>{compliment}</blockquote><small>Следующий комплимент откроется завтра</small></div><Heart fill="currentColor"/></section>
    <div className="home-grid"><Tamagotchi/><section className="panel next-event"><p className="eyebrow">БЛИЖАЙШАЯ ГЛАВА</p><h2>Калининград</h2><div className="date-big"><b>18</b><span>СЕНТЯБРЯ<br/>2026</span></div><p>Расстояние временно перестанет существовать.</p><div className="route"><MapPin/><i/><Heart fill="currentColor"/></div></section></div>
    <section className="recent"><div className="section-heading"><div><p className="eyebrow">СОХРАНЁННЫЕ МОМЕНТЫ</p><h2>Последние фотографии</h2></div><button onClick={()=>setView('gallery')}>Смотреть все →</button></div>{photos.length?<div className="photo-row">{photos.slice(0,4).map(p=><figure key={p.id}><img src={p.image_url}/><figcaption><b>{p.title}</b><span>{p.category}</span></figcaption></figure>)}</div>:<Empty icon={Camera} text="Ваши первые фотографии появятся здесь"/>}</section>
  </div>
}

function Museum({artifacts}:{artifacts:Artifact[]}) { return <div className="page"><section className="museum-intro"><p className="eyebrow">ЦИФРОВОЙ МУЗЕЙ ОТНОШЕНИЙ</p><h1>Добро пожаловать<br/>в нашу историю.</h1><p>Здесь хранятся моменты, благодаря которым «ты» и «я» стали «мы».</p><div className="together"><Clock3/><div><b>{daysBetween(togetherSince)} дней</b><span>мы выбираем друг друга</span></div></div></section>
  <section className="room-grid">{museumRooms.map(r=><article key={r.id}><span>{r.number}</span><p>{r.subtitle}</p><h2>{r.title}</h2><div className="red-line"/><p>{r.text}</p></article>)}</section>
  <section className="timeline-section"><div className="section-heading"><div><p className="eyebrow">АРХИВ ПАМЯТИ</p><h2>Хронология отношений</h2></div></div><div className="timeline">{timeline.map((e,i)=><article key={e.date} className={e.future?'future':''}><div className="timeline-dot">{e.future?<Clock3/>:<Heart fill="currentColor"/>}</div><div><time>{e.date}</time><h3>{e.title}</h3><p>{e.text}</p></div><span>{String(i+1).padStart(2,'0')}</span></article>)}</div></section>
  <section className="artifacts"><div className="section-heading"><div><p className="eyebrow">ЭКСПОНАТЫ</p><h2>То, что важно</h2></div></div>{artifacts.length?<div className="artifact-grid">{artifacts.map(a=><a key={a.id} href={a.link_url||a.file_url} target="_blank"><Archive/><b>{a.title}</b><span>{a.description}</span></a>)}</div>:<Empty icon={Archive} text="Первый экспонат ещё ждёт своего места"/>}</section>
  <section className="capsule"><div><p className="eyebrow">КАПСУЛА ВРЕМЕНИ</p><h2>Письмо после Калининграда</h2><p>Некоторые слова должны дождаться правильного момента. Эта капсула откроется после вашей встречи.</p></div><div className="capsule-lock"><Clock3/><span>Запечатано</span></div></section></div> }

function Gallery({photos}:{photos:Photo[]}) { const [cat,setCat]=useState('Все');const cats=['Все',...new Set(photos.map(p=>p.category))];const shown=cat==='Все'?photos:photos.filter(p=>p.category===cat);return <div className="page content-page"><PageTitle eyebrow="НАША ГАЛЕРЕЯ" title="Моменты, которые остаются." text="Фотографии и скриншоты вашей общей истории."/><div className="filters">{cats.map(c=><button className={cat===c?'active':''} onClick={()=>setCat(c)} key={c}>{c}</button>)}</div>{shown.length?<div className="gallery-grid">{shown.map(p=><figure key={p.id}><img src={p.image_url}/><figcaption><span>{p.category}</span><h3>{p.title}</h3><p>{p.description}</p></figcaption></figure>)}</div>:<Empty icon={Camera} text="В этой категории пока нет фотографий"/>}</div> }

function Movies({movies}:{movies:Movie[]}) { const [tab,setTab]=useState<'watched'|'planned'>('watched');const list=movies.filter(m=>m.status===tab);return <div className="page content-page"><PageTitle eyebrow="НАШ КИНОЗАЛ" title="Фильмы, просмотренные вместе." text="Оценки, любимые моменты и то, что ещё только предстоит посмотреть."/><div className="filters"><button className={tab==='watched'?'active':''} onClick={()=>setTab('watched')}>Просмотрено</button><button className={tab==='planned'?'active':''} onClick={()=>setTab('planned')}>Хотим посмотреть</button></div>{list.length?<div className="movie-grid">{list.map(m=><article key={m.id}><div className="poster">{m.poster_url?<img src={m.poster_url}/>:<Film/>}</div><span>{m.status==='watched'?'ПРОСМОТРЕНО':'В ПЛАНАХ'}</span><h3>{m.title}</h3>{m.status==='watched'&&<div className="ratings"><b>thugger · {m.thugger_rating||'—'}/10</b><b>vichka · {m.vichka_rating||'—'}/10</b></div>}<p>{m.comment}</p>{m.favorite_moments&&<small>Любимый момент: {m.favorite_moments}</small>}</article>)}</div>:<Empty icon={Clapperboard} text="Добавьте первый фильм через управление"/>}</div> }

function GalaxyPage(){return <div className="page galaxy-page"><PageTitle eyebrow="VICHKA GALAXY" title="Галактика, названная в её честь." text="В центре этой вселенной — сердце из тысяч частиц. Его можно вращать и рассматривать со всех сторон."/><Galaxy/></div>}

function Admin({photos,movies,artifacts,reload}:{photos:Photo[];movies:Movie[];artifacts:Artifact[];reload:()=>void}) {const [tab,setTab]=useState<'photos'|'movies'|'artifacts'>('photos');return <div className="page content-page"><PageTitle eyebrow="ОБЩЕЕ УПРАВЛЕНИЕ" title="Ваш архив — ваши правила." text="Оба аккаунта могут добавлять и удалять содержимое."/><div className="admin-tabs"><button className={tab==='photos'?'active':''} onClick={()=>setTab('photos')}><Camera/>Фотографии</button><button className={tab==='movies'?'active':''} onClick={()=>setTab('movies')}><Clapperboard/>Фильмы</button><button className={tab==='artifacts'?'active':''} onClick={()=>setTab('artifacts')}><Archive/>Экспонаты</button></div>{tab==='photos'&&<PhotoAdmin items={photos} reload={reload}/>} {tab==='movies'&&<MovieAdmin items={movies} reload={reload}/>} {tab==='artifacts'&&<ArtifactAdmin items={artifacts} reload={reload}/>}</div>}

function PhotoAdmin({items,reload}:{items:Photo[];reload:()=>void}) {
  const [busy,setBusy]=useState(false)
  async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget),file=f.get('file') as File;const path=filePath(file);const up=await supabase.storage.from('memories').upload(path,file);if(!up.error){const {data}=supabase.storage.from('memories').getPublicUrl(path);await supabase.from('photos').insert({title:f.get('title'),description:f.get('description'),category:f.get('category'),image_url:data.publicUrl,storage_path:path})}setBusy(false);e.currentTarget.reset();reload()}
  async function edit(item:Photo){const title=prompt('Название фотографии',item.title);if(title===null)return;const category=prompt('Категория',item.category);if(category===null)return;const description=prompt('Комментарий',item.description||'');if(description===null)return;await supabase.from('photos').update({title,category,description}).eq('id',item.id);reload()}
  async function remove(id:string){if(!confirm('Удалить эту фотографию?'))return;await supabase.from('photos').delete().eq('id',id);reload()}
  return <AdminBlock title="Добавить фотографию"><form className="admin-form" onSubmit={add}><input name="title" placeholder="Название фотографии" required/><input name="category" placeholder="Категория (можно создать новую)" required/><textarea name="description" placeholder="Комментарий к фотографии"/><input name="file" type="file" accept="image/*" required/><button className="primary" disabled={busy}><Plus/> {busy?'Загружаем…':'Добавить'}</button></form><div className="manage-list">{items.map(item=><div key={item.id}><span><b>{item.title}</b><small>{item.category} · {item.description}</small></span><div><button onClick={()=>edit(item)} aria-label={`Изменить ${item.title}`}><Edit3/></button><button onClick={()=>remove(item.id)} aria-label={`Удалить ${item.title}`}><Trash2/></button></div></div>)}</div></AdminBlock>
}
function MovieAdmin({items,reload}:{items:Movie[];reload:()=>void}) {async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),file=f.get('file') as File;let poster_url='';if(file.size){const path=filePath(file);const up=await supabase.storage.from('memories').upload(path,file);if(!up.error)poster_url=supabase.storage.from('memories').getPublicUrl(path).data.publicUrl}await supabase.from('movies').insert({title:f.get('title'),status:f.get('status'),thugger_rating:Number(f.get('thugger_rating'))||null,vichka_rating:Number(f.get('vichka_rating'))||null,comment:f.get('comment'),favorite_moments:f.get('favorite_moments'),poster_url});e.currentTarget.reset();reload()}return <AdminBlock title="Добавить фильм"><form className="admin-form" onSubmit={add}><input name="title" placeholder="Название фильма" required/><select name="status"><option value="watched">Просмотрено</option><option value="planned">Хотим посмотреть</option></select><div className="two"><input name="thugger_rating" type="number" min="1" max="10" placeholder="Оценка thugger"/><input name="vichka_rating" type="number" min="1" max="10" placeholder="Оценка vichka"/></div><textarea name="comment" placeholder="Комментарий или воспоминание"/><input name="favorite_moments" placeholder="Любимые персонажи или моменты"/><input name="file" type="file" accept="image/*"/><button className="primary"><Plus/>Добавить фильм</button></form><ManageList items={items} reload={reload} table="movies"/></AdminBlock>}
function ArtifactAdmin({items,reload}:{items:Artifact[];reload:()=>void}) {async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),file=f.get('file') as File;let file_url='';if(file.size){const path=filePath(file);const up=await supabase.storage.from('memories').upload(path,file);if(!up.error)file_url=supabase.storage.from('memories').getPublicUrl(path).data.publicUrl}await supabase.from('artifacts').insert({title:f.get('title'),description:f.get('description'),link_url:f.get('link_url'),file_url});e.currentTarget.reset();reload()}return <AdminBlock title="Добавить экспонат"><form className="admin-form" onSubmit={add}><input name="title" placeholder="Название экспоната" required/><textarea name="description" placeholder="История или описание"/><input name="link_url" type="url" placeholder="Памятная ссылка (необязательно)"/><input name="file" type="file"/><button className="primary"><Plus/>Добавить экспонат</button></form><ManageList items={items} reload={reload} table="artifacts"/></AdminBlock>}
function AdminBlock({title,children}:{title:string;children:React.ReactNode}){return <section className="admin-block"><h2>{title}</h2>{children}</section>}
function ManageList({items,table,reload}:{items:{id:string;title:string}[];table:string;reload:()=>void}){async function remove(id:string){if(!confirm('Удалить этот материал?'))return;await supabase.from(table).delete().eq('id',id);reload()}return <div className="manage-list">{items.map(i=><div key={i.id}><span>{i.title}</span><button onClick={()=>remove(i.id)} aria-label={`Удалить ${i.title}`}><Trash2/></button></div>)}</div>}

function ProfileView({profile,reload}:{profile:Profile|null;reload:()=>void}){const [message,setMessage]=useState('');async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),file=f.get('avatar') as File;let avatar_url=profile?.avatar_url||'';if(file.size){const path=filePath(file);const up=await supabase.storage.from('memories').upload(path,file);if(!up.error)avatar_url=supabase.storage.from('memories').getPublicUrl(path).data.publicUrl}await supabase.from('profiles').update({display_name:f.get('display_name'),avatar_url}).eq('id',profile?.id);const password=String(f.get('password')||'');if(password)await supabase.auth.updateUser({password});setMessage('Профиль сохранён');reload()}return <div className="page content-page profile-page"><PageTitle eyebrow="ПРОФИЛЬ" title={profile?.display_name||'Ваш профиль'} text="Имя, аватар и пароль видите и меняете только вы."/><form className="admin-form profile-form" onSubmit={save}><label>Отображаемое имя<input name="display_name" defaultValue={profile?.display_name}/></label><label>Новая аватарка<input name="avatar" type="file" accept="image/*"/></label><label>Новый пароль<input name="password" type="password" minLength={8} placeholder="Оставьте пустым, если менять не нужно"/></label>{message&&<p className="success">{message}</p>}<button className="primary">Сохранить изменения</button><button type="button" className="secondary danger" onClick={()=>supabase.auth.signOut()}><LogOut/>Выйти из аккаунта</button></form></div>}

function CalendarView(){const months=useMemo(()=>{const out:{label:string;events:typeof timeline}[]=[];for(const e of timeline){const [,m,y]=e.date.split('.');const key=`${m}.${y}`;let row=out.find(x=>x.label===key);if(!row){row={label:key,events:[]};out.push(row)}row.events.push(e)}return out},[]);return <div className="page content-page"><PageTitle eyebrow="КАЛЕНДАРЬ ОТНОШЕНИЙ" title="Наши важные даты." text="События, годовщины и дни, которые навсегда стали особенными."/><div className="calendar-grid">{months.map(month=><section key={month.label}><header><CalendarDays/><b>{month.label}</b></header>{month.events.map(event=><article key={event.date} className={event.future?'future':''}><time>{event.date.slice(0,2)}</time><div><h3>{event.title}</h3><p>{event.text}</p></div></article>)}</section>)}</div><section className="anniversary"><Heart fill="currentColor"/><div><p className="eyebrow">СЛЕДУЮЩАЯ ГОДОВЩИНА</p><h2>07 июля 2027</h2><span>Один год нашей истории</span></div></section></div>}
function PageTitle({eyebrow,title,text}:{eyebrow:string;title:string;text:string}){return <section className="page-title"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></section>}
function Empty({icon:Icon,text}:{icon:typeof Camera;text:string}){return <div className="empty"><Icon/><b>{text}</b><span>Добавить содержимое можно в разделе «Управление»</span></div>}
